/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.edinarobotics.scouting.gui;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author aoneill
 */
public class TeamInputPanel extends JPanel
{
  private static String TEAM_LABEL_TEXT = "Team:";
  private static String PENALTIES_LABEL_TEXT = "Penalties:";
  private static String COMMENTS_LABEL_TEXT = "Comments:";
  
  private static String PYRAMID_GOAL_LABEL_TEXT = "Pyramid Goal:";
  private static String HIGH_GOAL_LABEL_TEXT = "High Goal:";
  private static String MIDDLE_GOAL_LABEL_TEXT = "Middle Goal";
  private static String LOW_GOAL_LABEL_TEXT = "Low Goal:";
  
  private static String FRISBEES_SHOT_LABEL_TEXT = "Frisbees Shot:";
  
  private static int AUTO_HIGH_GOAL_MULTIPLIER = 1;
 
  
  private Color borderColor = Color.GRAY;
  
  /**
   * Creates new form NewJPanel
   */
  public TeamInputPanel()//Color color) 
  {
    //borderColor = color;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tabbedPanel = new javax.swing.JTabbedPane();
    autoJPanel = new javax.swing.JPanel();
    autoHighGoalLabel = new javax.swing.JLabel();
    autoHighGoalInput = new javax.swing.JTextField();
    autoMiddleGoalLabel = new javax.swing.JLabel();
    autoMiddleGoalInput = new javax.swing.JTextField();
    autoLowGoalLabel = new javax.swing.JLabel();
    autoLowGoalInput = new javax.swing.JTextField();
    autoFrisbeesShotLabel = new javax.swing.JLabel();
    autoFrisbeesShotInput = new javax.swing.JTextField();
    teleopJPanel = new javax.swing.JPanel();
    teleopHighGoalInput = new javax.swing.JTextField();
    teleopHighGoalLabel = new javax.swing.JLabel();
    teleopMiddleGoalLabel = new javax.swing.JLabel();
    teleopMiddleGoalInput = new javax.swing.JTextField();
    teleopLowGoalInput = new javax.swing.JTextField();
    teleopLowGoalLabel = new javax.swing.JLabel();
    teleopFrisbeesShotLabel = new javax.swing.JLabel();
    teleopFrisbeesShotInput = new javax.swing.JTextField();
    teleopPyramidGoalLabel = new javax.swing.JLabel();
    teleopPyramidGoalInput = new javax.swing.JTextField();
    comentsJPanel = new javax.swing.JPanel();
    commentsLabel = new javax.swing.JLabel();
    commentsScrollPane = new javax.swing.JScrollPane();
    commentTextArea = new javax.swing.JTextArea();
    teamLabel = new javax.swing.JLabel();
    teamInput = new javax.swing.JTextField();
    penaltiesInput = new javax.swing.JTextField();
    penaltiesLabel = new javax.swing.JLabel();

    setBorder(new javax.swing.border.LineBorder(borderColor, 4, true));
    setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

    tabbedPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    tabbedPanel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N

    autoHighGoalLabel.setText(HIGH_GOAL_LABEL_TEXT);

    autoMiddleGoalLabel.setText(MIDDLE_GOAL_LABEL_TEXT);

    autoLowGoalLabel.setText(LOW_GOAL_LABEL_TEXT);

    autoFrisbeesShotLabel.setText(FRISBEES_SHOT_LABEL_TEXT);

    org.jdesktop.layout.GroupLayout autoJPanelLayout = new org.jdesktop.layout.GroupLayout(autoJPanel);
    autoJPanel.setLayout(autoJPanelLayout);
    autoJPanelLayout.setHorizontalGroup(
      autoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(autoJPanelLayout.createSequentialGroup()
        .addContainerGap(57, Short.MAX_VALUE)
        .add(autoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(autoJPanelLayout.createSequentialGroup()
            .add(autoHighGoalLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(autoHighGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(autoJPanelLayout.createSequentialGroup()
            .add(autoMiddleGoalLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(autoMiddleGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(autoJPanelLayout.createSequentialGroup()
            .add(autoLowGoalLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(autoLowGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(autoJPanelLayout.createSequentialGroup()
            .add(autoFrisbeesShotLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(autoFrisbeesShotInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(58, Short.MAX_VALUE))
    );
    autoJPanelLayout.setVerticalGroup(
      autoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(autoJPanelLayout.createSequentialGroup()
        .add(3, 3, 3)
        .add(autoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(autoHighGoalLabel)
          .add(autoHighGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(3, 3, 3)
        .add(autoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(autoMiddleGoalLabel)
          .add(autoMiddleGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(3, 3, 3)
        .add(autoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(autoLowGoalLabel)
          .add(autoLowGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(9, 9, 9)
        .add(autoJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(autoFrisbeesShotLabel)
          .add(autoFrisbeesShotInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(62, 62, 62))
    );

    tabbedPanel.addTab("Autonomous", autoJPanel);

    teleopHighGoalLabel.setText(HIGH_GOAL_LABEL_TEXT);

    teleopMiddleGoalLabel.setText(MIDDLE_GOAL_LABEL_TEXT);

    teleopLowGoalLabel.setText(LOW_GOAL_LABEL_TEXT);

    teleopFrisbeesShotLabel.setText(FRISBEES_SHOT_LABEL_TEXT);

    teleopPyramidGoalLabel.setText(PYRAMID_GOAL_LABEL_TEXT);

    org.jdesktop.layout.GroupLayout teleopJPanelLayout = new org.jdesktop.layout.GroupLayout(teleopJPanel);
    teleopJPanel.setLayout(teleopJPanelLayout);
    teleopJPanelLayout.setHorizontalGroup(
      teleopJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(teleopJPanelLayout.createSequentialGroup()
        .addContainerGap(57, Short.MAX_VALUE)
        .add(teleopJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(teleopJPanelLayout.createSequentialGroup()
            .add(teleopHighGoalLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(teleopHighGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(teleopJPanelLayout.createSequentialGroup()
            .add(teleopMiddleGoalLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(teleopMiddleGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(teleopJPanelLayout.createSequentialGroup()
            .add(teleopLowGoalLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(teleopLowGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(teleopJPanelLayout.createSequentialGroup()
            .add(teleopFrisbeesShotLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(teleopFrisbeesShotInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(teleopJPanelLayout.createSequentialGroup()
            .add(teleopPyramidGoalLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(teleopPyramidGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(58, Short.MAX_VALUE))
    );
    teleopJPanelLayout.setVerticalGroup(
      teleopJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(teleopJPanelLayout.createSequentialGroup()
        .add(3, 3, 3)
        .add(teleopJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(teleopPyramidGoalLabel)
          .add(teleopPyramidGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(3, 3, 3)
        .add(teleopJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(teleopHighGoalLabel)
          .add(teleopHighGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(3, 3, 3)
        .add(teleopJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(teleopMiddleGoalLabel)
          .add(teleopMiddleGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(3, 3, 3)
        .add(teleopJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(teleopLowGoalLabel)
          .add(teleopLowGoalInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(9, 9, 9)
        .add(teleopJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(teleopFrisbeesShotLabel)
          .add(teleopFrisbeesShotInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(31, 31, 31))
    );

    tabbedPanel.addTab("Tele-Op / End Game", teleopJPanel);

    commentsLabel.setText(COMMENTS_LABEL_TEXT);

    commentTextArea.setColumns(18);
    commentTextArea.setRows(5);
    commentsScrollPane.setViewportView(commentTextArea);

    org.jdesktop.layout.GroupLayout comentsJPanelLayout = new org.jdesktop.layout.GroupLayout(comentsJPanel);
    comentsJPanel.setLayout(comentsJPanelLayout);
    comentsJPanelLayout.setHorizontalGroup(
      comentsJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(comentsJPanelLayout.createSequentialGroup()
        .add(14, 14, 14)
        .add(comentsJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(commentsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 252, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(commentsLabel))
        .add(14, 14, 14))
    );
    comentsJPanelLayout.setVerticalGroup(
      comentsJPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(comentsJPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(commentsLabel)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 7, Short.MAX_VALUE)
        .add(commentsScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(33, Short.MAX_VALUE))
    );

    tabbedPanel.addTab("Comments", comentsJPanel);

    teamLabel.setText(TEAM_LABEL_TEXT);

    penaltiesLabel.setText(PENALTIES_LABEL_TEXT);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .add(3, 3, 3)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
          .add(layout.createSequentialGroup()
            .add(penaltiesLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(penaltiesInput))
          .add(layout.createSequentialGroup()
            .add(teamLabel)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(teamInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(tabbedPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 301, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(3, 3, 3))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .add(3, 3, 3)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(teamLabel)
          .add(teamInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(tabbedPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(penaltiesLabel)
          .add(penaltiesInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .add(3, 3, 3))
    );
  }// </editor-fold>//GEN-END:initComponents

  public int getAutoScore()
  {
    return 0;
  }
  
  public int getAutoScore2()
  {
    return 0;
  }
  
  public int getAutoScore3()
  {
    return 0;
  }
  
  public void setBorderColor(Color color)
  {
    borderColor = color;
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField autoFrisbeesShotInput;
  private javax.swing.JLabel autoFrisbeesShotLabel;
  private javax.swing.JTextField autoHighGoalInput;
  private javax.swing.JLabel autoHighGoalLabel;
  private javax.swing.JPanel autoJPanel;
  private javax.swing.JTextField autoLowGoalInput;
  private javax.swing.JLabel autoLowGoalLabel;
  private javax.swing.JTextField autoMiddleGoalInput;
  private javax.swing.JLabel autoMiddleGoalLabel;
  private javax.swing.JPanel comentsJPanel;
  private javax.swing.JTextArea commentTextArea;
  private javax.swing.JLabel commentsLabel;
  private javax.swing.JScrollPane commentsScrollPane;
  private javax.swing.JTextField penaltiesInput;
  private javax.swing.JLabel penaltiesLabel;
  private javax.swing.JTabbedPane tabbedPanel;
  private javax.swing.JTextField teamInput;
  private javax.swing.JLabel teamLabel;
  private javax.swing.JTextField teleopFrisbeesShotInput;
  private javax.swing.JLabel teleopFrisbeesShotLabel;
  private javax.swing.JTextField teleopHighGoalInput;
  private javax.swing.JLabel teleopHighGoalLabel;
  private javax.swing.JPanel teleopJPanel;
  private javax.swing.JTextField teleopLowGoalInput;
  private javax.swing.JLabel teleopLowGoalLabel;
  private javax.swing.JTextField teleopMiddleGoalInput;
  private javax.swing.JLabel teleopMiddleGoalLabel;
  private javax.swing.JTextField teleopPyramidGoalInput;
  private javax.swing.JLabel teleopPyramidGoalLabel;
  // End of variables declaration//GEN-END:variables
}
